name:                daily-coding-problem-hs
version:             0.1.0.0
github:              "frndmg/daily-coding-problem-hs"
license:             BSD3
author:              "Fernando Martínez González"
maintainer:          "frndmartinezglez@gmail.com"
copyright:           "2021 Fernando Martínez González"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/frndmg/daily-coding-problem-hs#readme>

dependencies:
- base >= 4.7 && < 5
- heaps

library:
  source-dirs: src

tests:
  daily-coding-problem-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - daily-coding-problem-hs
    - hspec
    - hspec-contrib
    - QuickCheck
